using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using LegendOfZed.Overworld;
using UnityEditor;
using UnityEngine;

namespace LegendOfZed.Editor
{
    public static class ZedV30OverworldArtAuditAndCatalogSetup
    {
        private const string CatalogFolder = "Assets/LegendOfZed/Overworld/ArtCatalog";
        private const string CatalogPath = CatalogFolder + "/ZedOverworldArtCatalog.asset";
        private const string ReportPath = "Assets/LegendOfZed/ReadMeDocs/Zed_v3.0_OverworldArtCatalog_AuditReport.md";

        [MenuItem("Legend of Zed/Setup/Overworld/v3.0 Build Overworld Art Catalog")]
        public static void BuildOverworldArtCatalog()
        {
            EnsureFolders();

            ZedOverworldArtCatalog catalog = AssetDatabase.LoadAssetAtPath<ZedOverworldArtCatalog>(CatalogPath);
            if (catalog == null)
            {
                catalog = ScriptableObject.CreateInstance<ZedOverworldArtCatalog>();
                AssetDatabase.CreateAsset(catalog, CatalogPath);
            }

            catalog.Clear();

            string[] prefabGuids = AssetDatabase.FindAssets("t:Prefab", new[] { "Assets" });
            HashSet<GameObject> cataloged = new HashSet<GameObject>();
            List<string> uncategorizedUseful = new List<string>();

            for (int i = 0; i < prefabGuids.Length; i++)
            {
                string path = AssetDatabase.GUIDToAssetPath(prefabGuids[i]);
                if (ShouldSkipPath(path))
                {
                    continue;
                }

                GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (prefab == null)
                {
                    continue;
                }

                catalog.TotalScannedPrefabs++;

                bool added = CategorizePrefab(catalog, prefab, path);
                if (added)
                {
                    cataloged.Add(prefab);
                }
                else if (LooksPotentiallyUseful(path, prefab.name))
                {
                    uncategorizedUseful.Add(path);
                }
            }

            catalog.TotalCatalogedPrefabs = cataloged.Count;
            catalog.LastAuditTime = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            catalog.Notes =
                "Generated by v3.0 art audit. Review this catalog manually before wiring it into generation. " +
                "This pass does not place art or change generator behavior.";

            EditorUtility.SetDirty(catalog);
            AssetDatabase.SaveAssets();

            WriteAuditReport(catalog, uncategorizedUseful);

            Selection.activeObject = catalog;
            EditorGUIUtility.PingObject(catalog);

            Debug.Log("v3.0 overworld art catalog built. Scanned=" + catalog.TotalScannedPrefabs + " Cataloged=" + catalog.TotalCatalogedPrefabs + " Asset=" + CatalogPath);
        }

        [MenuItem("Legend of Zed/Setup/Overworld/v3.0 Select Overworld Art Catalog")]
        public static void SelectOverworldArtCatalog()
        {
            ZedOverworldArtCatalog catalog = AssetDatabase.LoadAssetAtPath<ZedOverworldArtCatalog>(CatalogPath);
            if (catalog == null)
            {
                Debug.LogWarning("No overworld art catalog found. Run v3.0 Build Overworld Art Catalog first.");
                return;
            }

            Selection.activeObject = catalog;
            EditorGUIUtility.PingObject(catalog);
        }

        [MenuItem("Legend of Zed/Setup/Overworld/v3.0 Validate Overworld Art Catalog")]
        public static void ValidateOverworldArtCatalog()
        {
            ZedOverworldArtCatalog catalog = AssetDatabase.LoadAssetAtPath<ZedOverworldArtCatalog>(CatalogPath);
            if (catalog == null)
            {
                Debug.LogWarning("v3.0 validation failed: missing catalog at " + CatalogPath);
                return;
            }

            int warnings = 0;

            ValidateCategory("Road straight", catalog.RoadStraightPrefabs, ref warnings);
            ValidateCategory("Road intersection", catalog.RoadIntersectionPrefabs, ref warnings);
            ValidateCategory("Sidewalk straight", catalog.SidewalkStraightPrefabs, ref warnings);
            ValidateCategory("Buildings", catalog.BuildingPrefabs, ref warnings);
            ValidateCategory("Grass / park ground", catalog.GrassOrParkGroundPrefabs, ref warnings);
            ValidateCategory("Trees", catalog.TreePrefabs, ref warnings);
            ValidateCategory("Bushes", catalog.BushPrefabs, ref warnings);
            ValidateCategory("Vehicles", catalog.VehiclePrefabs, ref warnings);
            ValidateCategory("Paper debris", catalog.PaperDebrisPrefabs, ref warnings);

            if (warnings == 0)
            {
                Debug.Log("v3.0 overworld art catalog validation passed. Cataloged=" + catalog.TotalCatalogedPrefabs + ".");
            }
            else
            {
                Debug.LogWarning("v3.0 overworld art catalog validation finished with " + warnings + " warning(s). Catalog still may be usable, but review missing categories.");
            }
        }

        private static bool CategorizePrefab(ZedOverworldArtCatalog catalog, GameObject prefab, string path)
        {
            string haystack = (path + " " + prefab.name).ToLowerInvariant();
            bool added = false;

            if (ContainsAny(haystack, "road_intersection", "intersection", "road_cross", "crossroad"))
                added |= AddUnique(catalog.RoadIntersectionPrefabs, prefab);
            else if (ContainsAny(haystack, "road_crossing", "crossing", "zebra"))
                added |= AddUnique(catalog.RoadCrossingPrefabs, prefab);
            else if (ContainsAny(haystack, "road", "street"))
                added |= AddUnique(catalog.RoadStraightPrefabs, prefab);

            if (ContainsAny(haystack, "sidewalk_corner", "pavement_corner"))
                added |= AddUnique(catalog.SidewalkCornerPrefabs, prefab);
            else if (ContainsAny(haystack, "sidewalk_edge", "pavement_edge", "curb"))
                added |= AddUnique(catalog.SidewalkEdgePrefabs, prefab);
            else if (ContainsAny(haystack, "sidewalk", "pavement"))
                added |= AddUnique(catalog.SidewalkStraightPrefabs, prefab);

            if (ContainsAny(haystack, "police", "hospital", "station", "shop", "store", "school", "church", "garage"))
                added |= AddUnique(catalog.SpecialBuildingPrefabs, prefab);

            if (ContainsAny(haystack, "bld", "building", "house", "apartment", "skyscraper", "facade"))
                added |= AddUnique(catalog.BuildingPrefabs, prefab);

            if (ContainsAny(haystack, "door", "entrance", "portal"))
                added |= AddUnique(catalog.DoorOrEntrancePrefabs, prefab);

            if (ContainsAny(haystack, "sign", "billboard"))
                added |= AddUnique(catalog.SignPrefabs, prefab);

            if (ContainsAny(haystack, "grass", "park_ground", "ground_grass", "lawn"))
                added |= AddUnique(catalog.GrassOrParkGroundPrefabs, prefab);

            if (ContainsAny(haystack, "park_path", "path", "trail"))
                added |= AddUnique(catalog.ParkPathPrefabs, prefab);

            if (ContainsAny(haystack, "tree", "palm"))
                added |= AddUnique(catalog.TreePrefabs, prefab);

            if (ContainsAny(haystack, "bush", "shrub", "hedge"))
                added |= AddUnique(catalog.BushPrefabs, prefab);

            if (ContainsAny(haystack, "bench"))
                added |= AddUnique(catalog.BenchPrefabs, prefab);

            if (ContainsAny(haystack, "police_car", "car_police", "veh_police", "vehicle_police"))
                added |= AddUnique(catalog.PoliceVehiclePrefabs, prefab);

            if (ContainsAny(haystack, "veh", "vehicle", "car", "truck", "van", "bus", "taxi", "ambulance"))
                added |= AddUnique(catalog.VehiclePrefabs, prefab);

            if (ContainsAny(haystack, "streetlight", "street_light", "lamp_post", "lampost"))
                added |= AddUnique(catalog.StreetLightPrefabs, prefab);

            if (ContainsAny(haystack, "traffic_light", "trafficlight"))
                added |= AddUnique(catalog.TrafficLightPrefabs, prefab);

            if (ContainsAny(haystack, "hydrant"))
                added |= AddUnique(catalog.HydrantPrefabs, prefab);

            if (ContainsAny(haystack, "mailbox", "mail_box"))
                added |= AddUnique(catalog.MailboxPrefabs, prefab);

            if (ContainsAny(haystack, "parking_meter", "parkingmeter", "meter"))
                added |= AddUnique(catalog.ParkingMeterPrefabs, prefab);

            if (ContainsAny(haystack, "power_box", "powerbox", "electrical", "junction"))
                added |= AddUnique(catalog.PowerBoxPrefabs, prefab);

            if (ContainsAny(haystack, "trashcan", "trash_can", "bin", "rubbish_bin"))
                added |= AddUnique(catalog.TrashCanPrefabs, prefab);

            if (ContainsAny(haystack, "dumpster", "skip"))
                added |= AddUnique(catalog.DumpsterOrSkipPrefabs, prefab);

            if (ContainsAny(haystack, "trash_heap", "trashpile", "trash_pile", "rubbish", "garbage"))
                added |= AddUnique(catalog.TrashHeapPrefabs, prefab);

            if (ContainsAny(haystack, "paper", "newspaper", "debris_paper"))
                added |= AddUnique(catalog.PaperDebrisPrefabs, prefab);

            if (ContainsAny(haystack, "barrier", "barricade", "cone"))
                added |= AddUnique(catalog.BarrierPrefabs, prefab);

            if (ContainsAny(haystack, "fence", "railing"))
                added |= AddUnique(catalog.FencePrefabs, prefab);

            if (!added && ContainsAny(haystack, "prop", "sm_prop"))
                added |= AddUnique(catalog.GenericPropPrefabs, prefab);

            return added;
        }

        private static void WriteAuditReport(ZedOverworldArtCatalog catalog, List<string> uncategorizedUseful)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("# v3.0 Overworld Art Catalog Audit Report");
            sb.AppendLine();
            sb.AppendLine("Generated: " + catalog.LastAuditTime);
            sb.AppendLine();
            sb.AppendLine("## Summary");
            sb.AppendLine();
            sb.AppendLine("- Scanned prefabs: " + catalog.TotalScannedPrefabs);
            sb.AppendLine("- Cataloged unique prefabs: " + catalog.TotalCatalogedPrefabs);
            sb.AppendLine("- Catalog asset: `" + CatalogPath + "`");
            sb.AppendLine();
            sb.AppendLine("## Category Counts");
            sb.AppendLine();
            AppendCount(sb, "Road straight", catalog.RoadStraightPrefabs);
            AppendCount(sb, "Road intersections", catalog.RoadIntersectionPrefabs);
            AppendCount(sb, "Road crossings", catalog.RoadCrossingPrefabs);
            AppendCount(sb, "Manholes", catalog.ManholePrefabs);
            AppendCount(sb, "Sidewalk straight", catalog.SidewalkStraightPrefabs);
            AppendCount(sb, "Sidewalk corners", catalog.SidewalkCornerPrefabs);
            AppendCount(sb, "Sidewalk edges", catalog.SidewalkEdgePrefabs);
            AppendCount(sb, "Buildings", catalog.BuildingPrefabs);
            AppendCount(sb, "Special buildings", catalog.SpecialBuildingPrefabs);
            AppendCount(sb, "Doors / entrances", catalog.DoorOrEntrancePrefabs);
            AppendCount(sb, "Signs", catalog.SignPrefabs);
            AppendCount(sb, "Grass / park ground", catalog.GrassOrParkGroundPrefabs);
            AppendCount(sb, "Park paths", catalog.ParkPathPrefabs);
            AppendCount(sb, "Trees", catalog.TreePrefabs);
            AppendCount(sb, "Bushes", catalog.BushPrefabs);
            AppendCount(sb, "Benches", catalog.BenchPrefabs);
            AppendCount(sb, "Vehicles", catalog.VehiclePrefabs);
            AppendCount(sb, "Police vehicles", catalog.PoliceVehiclePrefabs);
            AppendCount(sb, "Street lights", catalog.StreetLightPrefabs);
            AppendCount(sb, "Traffic lights", catalog.TrafficLightPrefabs);
            AppendCount(sb, "Hydrants", catalog.HydrantPrefabs);
            AppendCount(sb, "Mailboxes", catalog.MailboxPrefabs);
            AppendCount(sb, "Parking meters", catalog.ParkingMeterPrefabs);
            AppendCount(sb, "Power boxes", catalog.PowerBoxPrefabs);
            AppendCount(sb, "Trash cans", catalog.TrashCanPrefabs);
            AppendCount(sb, "Dumpsters / skips", catalog.DumpsterOrSkipPrefabs);
            AppendCount(sb, "Trash heaps", catalog.TrashHeapPrefabs);
            AppendCount(sb, "Paper debris", catalog.PaperDebrisPrefabs);
            AppendCount(sb, "Barriers", catalog.BarrierPrefabs);
            AppendCount(sb, "Fences", catalog.FencePrefabs);
            AppendCount(sb, "Generic props", catalog.GenericPropPrefabs);
            sb.AppendLine();

            sb.AppendLine("## Sample Prefabs");
            sb.AppendLine();
            AppendSamples(sb, "Road straight", catalog.RoadStraightPrefabs);
            AppendSamples(sb, "Sidewalk straight", catalog.SidewalkStraightPrefabs);
            AppendSamples(sb, "Buildings", catalog.BuildingPrefabs);
            AppendSamples(sb, "Special buildings", catalog.SpecialBuildingPrefabs);
            AppendSamples(sb, "Trees", catalog.TreePrefabs);
            AppendSamples(sb, "Vehicles", catalog.VehiclePrefabs);
            AppendSamples(sb, "Paper debris", catalog.PaperDebrisPrefabs);
            sb.AppendLine();

            sb.AppendLine("## Potentially Useful But Uncategorized");
            sb.AppendLine();
            if (uncategorizedUseful.Count == 0)
            {
                sb.AppendLine("None found.");
            }
            else
            {
                int max = Mathf.Min(uncategorizedUseful.Count, 50);
                for (int i = 0; i < max; i++)
                {
                    sb.AppendLine("- `" + uncategorizedUseful[i] + "`");
                }

                if (uncategorizedUseful.Count > max)
                {
                    sb.AppendLine("- ...and " + (uncategorizedUseful.Count - max) + " more.");
                }
            }

            sb.AppendLine();
            sb.AppendLine("## Notes");
            sb.AppendLine();
            sb.AppendLine("This audit only catalogs assets. It does not change generation, placement, player, zombies, weapons, portals, or NavMesh.");
            sb.AppendLine("Review `ZedOverworldArtCatalog.asset` manually before wiring it into the generator.");

            File.WriteAllText(ReportPath, sb.ToString());
            AssetDatabase.ImportAsset(ReportPath);
        }

        private static void AppendCount(StringBuilder sb, string label, List<GameObject> list)
        {
            sb.AppendLine("- " + label + ": " + CountNonNull(list));
        }

        private static void AppendSamples(StringBuilder sb, string label, List<GameObject> list)
        {
            sb.AppendLine("### " + label);
            sb.AppendLine();

            int written = 0;
            for (int i = 0; i < list.Count && written < 10; i++)
            {
                if (list[i] == null)
                {
                    continue;
                }

                string path = AssetDatabase.GetAssetPath(list[i]);
                sb.AppendLine("- `" + path + "`");
                written++;
            }

            if (written == 0)
            {
                sb.AppendLine("None.");
            }

            sb.AppendLine();
        }

        private static int CountNonNull(List<GameObject> list)
        {
            int count = 0;
            for (int i = 0; i < list.Count; i++)
            {
                if (list[i] != null)
                {
                    count++;
                }
            }

            return count;
        }

        private static void ValidateCategory(string label, List<GameObject> list, ref int warnings)
        {
            if (list == null || CountNonNull(list) == 0)
            {
                Debug.LogWarning("v3.0 catalog missing category: " + label);
                warnings++;
            }
        }

        private static bool AddUnique(List<GameObject> list, GameObject prefab)
        {
            if (prefab == null || list.Contains(prefab))
            {
                return false;
            }

            list.Add(prefab);
            return true;
        }

        private static bool ContainsAny(string haystack, params string[] needles)
        {
            for (int i = 0; i < needles.Length; i++)
            {
                if (haystack.Contains(needles[i]))
                {
                    return true;
                }
            }

            return false;
        }

        private static bool ShouldSkipPath(string path)
        {
            if (string.IsNullOrEmpty(path))
            {
                return true;
            }

            string lower = path.ToLowerInvariant();
            return lower.Contains("/editor/") ||
                   lower.Contains("/readmedocs/") ||
                   lower.Contains("/gizmos/") ||
                   lower.Contains("/resources/editor") ||
                   lower.Contains("syntypackagehelper") ||
                   lower.Contains("/weapon/") ||
                   lower.Contains("/weapondrop/") ||
                   lower.Contains("/projectiles/") ||
                   lower.Contains("/bullets/") ||
                   lower.Contains("/effects/") ||
                   lower.Contains("/fx/");
        }

        private static bool LooksPotentiallyUseful(string path, string name)
        {
            string haystack = (path + " " + name).ToLowerInvariant();
            return ContainsAny(haystack, "city", "urban", "street", "road", "sidewalk", "building", "prop", "park", "tree", "trash", "vehicle", "sign");
        }

        private static void EnsureFolders()
        {
            if (!AssetDatabase.IsValidFolder("Assets/LegendOfZed"))
            {
                AssetDatabase.CreateFolder("Assets", "LegendOfZed");
            }

            if (!AssetDatabase.IsValidFolder("Assets/LegendOfZed/Overworld"))
            {
                AssetDatabase.CreateFolder("Assets/LegendOfZed", "Overworld");
            }

            if (!AssetDatabase.IsValidFolder(CatalogFolder))
            {
                AssetDatabase.CreateFolder("Assets/LegendOfZed/Overworld", "ArtCatalog");
            }

            if (!AssetDatabase.IsValidFolder("Assets/LegendOfZed/ReadMeDocs"))
            {
                AssetDatabase.CreateFolder("Assets/LegendOfZed", "ReadMeDocs");
            }
        }
    }
}
